apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deploy_eks
  name: deploy_eks
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deploy_eks
  template:
    metadata:
      labels:
        app: deploy_eks
    spec:
      containers:
      - name: my-deploy-eks
        image: mounika1612/deploy_eks:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
          name: http
          protocol: TCP
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: deploy_eks
    k8s-app: deploy_eks
  name: deploy_eks
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8085
  type: LoadBalancer
  selector:
    app: deploy_eks
